// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHzKI92ku_apVyNcyK-8tiYHKXQ9jiDgA',
    appId: '1:957786893349:web:4d8b260683401dd00423cc',
    messagingSenderId: '957786893349',
    projectId: 'play-arena-e83d8',
    authDomain: 'play-arena-e83d8.firebaseapp.com',
    storageBucket: 'play-arena-e83d8.firebasestorage.app',
    measurementId: 'G-SLY0Z35BTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzKCnNo9zSZ9Y3oe0Opg2XRk4J5fkTMIQ',
    appId: '1:957786893349:android:8e5ba7f9ac4bc02a0423cc',
    messagingSenderId: '957786893349',
    projectId: 'play-arena-e83d8',
    storageBucket: 'play-arena-e83d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuXvVuuzndqusFkXmSMR4Df5NMjXXuPmU',
    appId: '1:957786893349:ios:80974ac2010d700a0423cc',
    messagingSenderId: '957786893349',
    projectId: 'play-arena-e83d8',
    storageBucket: 'play-arena-e83d8.firebasestorage.app',
    androidClientId: '957786893349-k0rm5am1cu8ig6uj43motbea85r7uih4.apps.googleusercontent.com',
    iosClientId: '957786893349-te2cq8sss12nfl85cu5ctaufvr3anjmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.playarena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuXvVuuzndqusFkXmSMR4Df5NMjXXuPmU',
    appId: '1:957786893349:ios:80974ac2010d700a0423cc',
    messagingSenderId: '957786893349',
    projectId: 'play-arena-e83d8',
    storageBucket: 'play-arena-e83d8.firebasestorage.app',
    androidClientId: '957786893349-k0rm5am1cu8ig6uj43motbea85r7uih4.apps.googleusercontent.com',
    iosClientId: '957786893349-te2cq8sss12nfl85cu5ctaufvr3anjmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.playarena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHzKI92ku_apVyNcyK-8tiYHKXQ9jiDgA',
    appId: '1:957786893349:web:a63bb1c5e341221e0423cc',
    messagingSenderId: '957786893349',
    projectId: 'play-arena-e83d8',
    authDomain: 'play-arena-e83d8.firebaseapp.com',
    storageBucket: 'play-arena-e83d8.firebasestorage.app',
    measurementId: 'G-F537SP9266',
  );
}
